cat src/html/assets/javascripts/plupload.js > src/html/assets/javascripts/releases/4.0.2/upload.js
cat src/html/assets/javascripts/plupload.html5.js >> src/html/assets/javascripts/releases/4.0.2/upload.js
cat src/html/assets/javascripts/jquery.plupload.queue.js >> src/html/assets/javascripts/releases/4.0.2/upload.js
cat src/html/assets/javascripts/openphoto-upload.js >> src/html/assets/javascripts/releases/4.0.2/upload.js
cat src/html/assets/themes/fabrizio1.0/javascripts/dropzone.js >> src/html/assets/javascripts/releases/4.0.2/upload.js

cat src/html/assets/themes/fabrizio1.0/javascripts/underscore-min.js > src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/modernizr.custom.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/backbone.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/bootstrap.min.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/jquery.color.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/x-editable/bootstrap-editable/js/bootstrap-editable.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/phpjs.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/overrides.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/namespace.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/route/Routes.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/model/Album.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/model/Batch.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/model/Notification.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/model/Profile.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/model/Photo.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/model/ProgressBar.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/model/Tag.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/collection/Album.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/collection/Profile.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/collection/Photo.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/collection/Tag.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/store/Albums.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/store/Profiles.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/store/Photos.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/store/Tags.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/Editable.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/BatchIndicator.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/AlbumCover.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/Notification.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/PhotoDetail.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/PhotoGallery.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/ProfileName.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/ProfilePhoto.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/ProgressBar.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/TagSearch.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/data/view/UserBadge.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/Lightbox.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/Util.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/Strings.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/Handlers.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/Highlight.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/Callbacks.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/Tutorial.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/Upload.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/op/Format.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/gallery.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/intro.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js
cat src/html/assets/themes/fabrizio1.0/javascripts/fabrizio.js >> src/html/assets/javascripts/releases/4.0.2/tbx.js